services:
  redis:
    image: redis:7.0.11-alpine
    container_name: redis

  celery:
    build:
      context: ./eshop
      dockerfile: dockerfile
    container_name: celery_container
    command: celery -A config.celery_base  worker -l INFO
    depends_on:
      - redis

  eshop:
    build:
      context: ./eshop
      dockerfile: dockerfile
    container_name: eshop_container

    command: python3 manage.py  runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
  stand_alone_celery:
    build:
      context: ./stand_alone_celery
      dockerfile: dockerfile
    container_name: stand_alone_celery_container

    command: celery -A celery_base worker -l INFO
    depends_on:
      - redis
